name: Debug stuff

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - run: |
          echo "$GITHUB_SERVER_URL"
          echo "${{ github.server_url }}"

          if [ "$GITHUB_SERVER_URL" != "https://github.com" ]; then
            echo "Not github.com"
          else
            echo "github.com"
          fi
